server:
  port: 8081
  undertow:
    decode-url: jdbc:mysql:///jrtq2025-his-db

spring:
  application:
    name: CarePlus-ApplicationRegistration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

ar:
  apiUrl:
    url: http://localhost:9091/SsaWebOperation/find/{ssn}
state: Pennsylvania
